server:
  port: 8080
spring:
  application:
    name: CookingService

  security:
    jwt:
      secret: secret
      expiration: 86400000 # 24 hours

  sql:
    init:
      mode: never
  datasource:
    url: jdbc:postgresql://localhost:8088/postgres
    username: postgres
    password: postgres

  jpa:
    database: postgresql

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: false