server:
  port: 8080
spring:
  application:
    name: CookingService


  sql:
    init:
      mode: embedded
  datasource:
    url: jdbc:postgresql://localhost:8088/postgres
    username: postgres
    password: postgres

  jpa:
    database: postgresql

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: false